### PR TITLE
Add Dockerfile and docker-compose.yml

### PR DESCRIPTION
**Pull request by acerioni**
⚠️ The `README.md` must be updated.

### CODE REVIEW

**Comment by cleherny** [comment]
Running the workflow of the quarry example with the Docker container is working fine.
I had first to install `nvidia-container-toolkit` to enable the access of the container to the gpu. I followed these procedures:
- https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-apt
- https://github.com/NVIDIA/nvidia-docker/issues/1243#issuecomment-694981577
- https://github.com/NVIDIA/nvidia-docker/issues/1034#issuecomment-520282450

I updated the README.md file of the quarry example on branch `ch/add-docker` and opened PR#15.

**Comment by acerioni** [comment]
Yes, I had to install `nvidia-container-toolkit` on the VM I'm working on as well.

**Comment by acerioni** [comment]
So... @cleherny can you please do a review to accept the pull request?

**Review by cleherny — CHANGES_REQUESTED** [review]
- You have added some functions such as the "DONE_MSG". For the sake of homogeneity I can add it to the quarry scripts as well (along by changing some logger.info to logger.success).
- From PEP8 (https://peps.python.org/pep-0008/) it is advised to separate imports:
image
for instance `import os, sys`
- The main README.md and the ones from swimming pool examples (environment and path to scripts) should be updated

**Comment by acerioni** [comment]
> It looks very nice! I have some minor comments:
> 
>     * You have added some functions such as the "DONE_MSG". For the sake of homogeneity, I can add it to the quarry scripts as well (along with changing some logger.info to logger.success). I can do it.
> 
>     * From PEP8 (https://peps.python.org/pep-0008/) it is advised to separate imports:
>       image
>       for instance `import os, sys`
> 
>     * The main README.md and the ones from swimming pool examples (environment and path to scripts) should be updated before being merged to master.

It's now done!

**Review by cleherny — APPROVED** [review]
After a final checking, it looks all good for me!

**Pull request merged**
