### PR TITLE
Multi class

### PR DESCRIPTION
**Pull request by GwenaelleSa**
*Goal*: Implement a multi-class detection.

This branch ensure that the class of the labels and detections are kept and controlled in the process.
An additional example is created to test the multi-class instance segmentation.

*Additional modification*
- Add a working directory to every script
- Add a debug mode to the training script
- Reorder functions alphabetically in misc.py

### CODE REVIEW

**Review by cleherny — CHANGES_REQUESTED** [review]
- I run all the examples (except swimming pool NE). There was some path and typo issues. You can see my comments inside the codes.
- The category and supercategory were not set for the quarry example, I did it on the branch `ch/multi-class_review`.
- When I run the detection workflow of the quarry example I get this error message:
image
May be we can switch it to a warning or not make it appears when proceeding to inference (no gt labels).
- When I run the script `assess_detections.py` I obtained recall value of 1 which is strange.
image

This is not the case with the `master` branch:
image
Can you check if you have observe the same issue?
- The is a `misc.py` script in the multi-class example and one in the 'helpers' folder. The one from the example have to be merged with the main one.
- Should we have only .gpkg files and no more .geojson files?

**Comment by GwenaelleSa** [comment]
@cleherny Did you run the detection workflow of the quarry example in debug or in full mode?

**Comment by cleherny** [comment]
> @cleherny Did you run the detection workflow of the quarry example in debug or in full mode?

I run it in full mode

**Comment by cleherny** [comment]
I have tested all the examples and the results are conforms. We are ready to merge.

**Review by acerioni — APPROVED** [review]
Everything's OK, great!

**Pull request merged**
